<?php
/**
 * Plugin Name: Wheel meta boxes
 *
 * @package s8-wheel-meta-boxes
 */

namespace s8\WP\WheelMetaBoxes;

// Adds an SVG with image load event to dispatch a custom event letting the UI code know
// that the canvas is available and whether it’s iframed.
add_filter( 'block_editor_settings_all', __NAMESPACE__ . '\add_canvas_informant', 10 );
function add_canvas_informant( $settings ) {
	if ( ! isset( $settings['styles'] ) ) {
		$settings['styles'] = [];
	}
	$markup = <<<HTML
		<svg>
			<image
				onload="
					const sameWindow = window.parent === window;
					(sameWindow ? window : window.parent).dispatchEvent(
						new CustomEvent('editorcanvascomplete', { detail: ! sameWindow })
					);
				"
				href="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
			/>
		</svg>
	HTML;
	$settings['styles'][] = [
		'assets'         => $markup,
		// The 'svgs' type is new in WP 6.3.
		'__unstableType' => 'svgs',
		// These styles aren’t generated by global styles, so this must be false or it’s
		// stripped out in gutenberg_get_block_editor_settings.
		'isGlobalStyles' => false,
	];
	return $settings;
}

add_action( 'enqueue_block_editor_assets', __NAMESPACE__ . '\\assets' );
function assets() {
	// Bails unless on 'post' screen (avoiding site editor).
	if ('post' !== get_current_screen()->base) return;

	wp_enqueue_script(
		's8-wheel-meta-boxes',
		plugins_url( 'wheel-meta-boxes.js', __FILE__ ),
		[
			'wp-data',
			'wp-editor',
			'wp-edit-post',
			'wp-preferences',
		],
		filemtime( plugin_dir_path( __FILE__ ) . 'wheel-meta-boxes.js' ),
		true,
	);
	wp_enqueue_script(
		's8-wheel-meta-boxes-sidebar',
		plugins_url( 'sidebar.js', __FILE__ ),
		[
			'wp-components',
			'wp-compose',
			'wp-data',
			'wp-editor',
			'wp-plugins',
			'wp-preferences',
		],
		filemtime( plugin_dir_path( __FILE__ ) . 'sidebar.js' ),
		true
	);
	wp_enqueue_style(
		's8-wheel-meta-boxes-sidebar',
		plugins_url( 'sidebar.css', __FILE__ ),
		[],
		filemtime( plugin_dir_path( __FILE__ ) . 'sidebar.css' )
	);
}
